In [4]:
import numpy as np
import hashlib

Name A: Aaryan Neupane

Name B: Anne Torgersen

In [5]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [6]:
unique_words = ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students'] # Enter the unique words list here

In [7]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma


Enter your created list of unique words:  ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']


Correct! Your dictionary matched!


In [8]:
Input_Matrix = np.zeros((10, 4), dtype = int) # Create an empty array of input matrix
print(Input_Matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
## Compute the values for the input matrix here ##
sentences = ["The Big Data platform for students is Blackboard","Questions on MinHash project by NTNU students is on Piazza",
             "NTNU Big Data platform are Blackboard and Piazza","The project data for students are on Blackboard not Piazza"]

# Loop through each word and each sentence
for i, word in enumerate(unique_words):
    for j, sentence in enumerate(sentences):
        if word in sentence.lower():  # Case-insensitive check for word presence
            Input_Matrix[i][j] = 1  # Update the value to 1 if word is present

print(Input_Matrix)

[[1 0 1 0]
 [1 0 1 1]
 [1 0 1 1]
 [0 1 0 0]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]]


In [10]:
Sig_M = np.full((3, 4), np.inf) # Create a MinHash signature matrix array with inf values
print(Sig_M)

[[inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]


In [2]:
# Generate hash functions

In [18]:
hash_1 = [5 ,6 ,7 ,8 ,9 ,10 ,1 ,2 ,3 ,4]
hash_2 = [9, 6, 3, 10, 7, 4, 1, 8, 5, 2]
hash_3 = [10, 7, 4, 1, 8, 5, 2, 9, 6, 3]
hash_list = [hash_1, hash_2, hash_3]

## Using the hash functions and the input matrix compute the MinHash signature matrix here ##
for i, r in enumerate(Input_Matrix):
    for j, c in enumerate(Input_Matrix):
        if 1 in r:
            for hi in hash_list:
                if hi[i] < Sig_M[j, i]:
                    Sig_M[j, i] = hi[i]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [12]:
# print the updated MinHash signature matrix

Sig_M

array([[3., 4., 3., 3.],
       [2., 5., 2., 2.],
       [3., 6., 3., 3.]])